# Generated by Django 4.2.6 on 2023-10-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_listcartproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListCartProduct',
        ),
    ]
