# Generated by Django 4.2.6 on 2023-10-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_product_image_relative_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
